### ISSUE TITLE
COU200 does not compile

### ISSUE THREAD

**Issue by Terry-4ever-i** [edmundreinhardt/bob-recursive-example#18]
Thanks for the video.  I did the full build but COU200 failed to compile.  I'm not sure why.  I copied into a SRCPF and it compiled!
Here's the messages
=== Create RPG Program [COU200]
/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf -f /home/tez/bob-recursive-example-master/QRPGSRC/COU200.RPG -o COU200 -l TEZBOB -c CRTRPGPGM -p "OPTION(*SRCDBG) TEXT()"
**✕ Failed to create COU200.PGM!**

Objects:             **1 failed** 106 succeed 107 total
 > Failed objects:    COU200.PGM
Build Completed!

**Comment by beckhamrryyaann** [comment]
Under your project directory there is a .logs/output.log file that will show you the compile spool file generated for that object.  That may point you in the right direction.

**Comment by edmundreinhardt** [comment]
Please get the latest copy of the the bob-recursive-example and install the latest copy of bob as these issues have been resolved for some time.
